version: '3.1'

services:

  microservice:
    image: experiencedevops/customerservice:latest 
    ports:
      - "9090:9090"
    networks:
      - all
    deploy:
      replicas: 1

  react:
    image: experiencedevops/reactapp:a04da60
    ports:
      - "9092:80"
    environment:
      - BASE_URL=/run/secrets/base-url
    secrets:
      - base-url
    networks:
      - all
    deploy:
      replicas: 3

  angular:
    image: experiencedevops/selfserviceapp:latest
    ports:
      - "80:80"
    environment:
      - API_URL=/run/secrets/base-url
    secrets:
      - base-url
    networks:
      - all
    deploy:
      replicas: 3
   
secrets:
  base-url:
    file: ./apiurl.txt

networks:
  all:
