version: '3.1'

services:

  microservice:
    image: experiencedevops/customerservice:latest 
    ports:
      - "9090:9090"
    networks:
      - all
    deploy:
      replicas: 1
      restart_policy:
	condition: on-failure

  react:
    image: experiencedevops/reactapp:79071df
    ports:
      - "9092:80"
    environment:
      - BASE_URL=/run/secrets/base-url
    secrets:
      - base-url
    networks:
      - all
    deploy:
      replicas: 3
      restart_policy:
	condition: on-failure

  angular:
    image: experiencedevops/selfserviceapp:latest
    ports:
      - "80:80"
    environment:
      - API_URL=/run/secrets/base-url
    secrets:
      - base-url
    networks:
      - all
    deploy:
      replicas: 3
      restart_policy:
	condition: on-failure
   
secrets:
  base-url:
    external: true

networks:
  all:
